# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thsr_ui.ui',
# licensing of 'thsr_ui.ui' applies.
#
# Created: Thu Feb 20 16:18:17 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1312, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b_send_bookingform = QtWidgets.QPushButton(self.centralwidget)
        self.b_send_bookingform.setGeometry(QtCore.QRect(340, 490, 75, 23))
        self.b_send_bookingform.setObjectName("b_send_bookingform")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 380, 241, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_securecode = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_securecode.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_securecode.setObjectName("gridLayout_securecode")
        self.b_generate_securecode = QtWidgets.QPushButton(self.centralwidget)
        self.b_generate_securecode.setGeometry(QtCore.QRect(340, 390, 75, 23))
        self.b_generate_securecode.setObjectName("b_generate_securecode")
        self.lineEdit_securecode = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_securecode.setGeometry(QtCore.QRect(100, 490, 239, 20))
        self.lineEdit_securecode.setObjectName("lineEdit_securecode")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 110, 271, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cB_depar_station = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cB_depar_station.setObjectName("cB_depar_station")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.cB_depar_station.addItem("")
        self.horizontalLayout.addWidget(self.cB_depar_station)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cB_arrive_station = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cB_arrive_station.setObjectName("cB_arrive_station")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.cB_arrive_station.addItem("")
        self.horizontalLayout.addWidget(self.cB_arrive_station)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.calendarWidget_departure = QtWidgets.QCalendarWidget(self.verticalLayoutWidget)
        self.calendarWidget_departure.setObjectName("calendarWidget_departure")
        self.verticalLayout.addWidget(self.calendarWidget_departure)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cB_depar_time = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cB_depar_time.setObjectName("cB_depar_time")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.cB_depar_time.addItem("")
        self.horizontalLayout_2.addWidget(self.cB_depar_time)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.listWidget_availableTrain = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_availableTrain.setGeometry(QtCore.QRect(420, 110, 391, 341))
        self.listWidget_availableTrain.setObjectName("listWidget_availableTrain")
        self.b_send_selectedtrain = QtWidgets.QPushButton(self.centralwidget)
        self.b_send_selectedtrain.setGeometry(QtCore.QRect(690, 460, 101, 31))
        self.b_send_selectedtrain.setObjectName("b_send_selectedtrain")
        self.lineEdit_ID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ID.setGeometry(QtCore.QRect(390, 20, 201, 31))
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_phone.setGeometry(QtCore.QRect(390, 60, 201, 31))
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.textEdit_result = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_result.setGeometry(QtCore.QRect(820, 110, 361, 341))
        self.textEdit_result.setObjectName("textEdit_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.b_send_bookingform.setText(QtWidgets.QApplication.translate("MainWindow", "送出表單", None, -1))
        self.b_generate_securecode.setText(QtWidgets.QApplication.translate("MainWindow", "產生驗證碼", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "起程站", None, -1))
        self.cB_depar_station.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "南港", None, -1))
        self.cB_depar_station.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "台北", None, -1))
        self.cB_depar_station.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "板橋", None, -1))
        self.cB_depar_station.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "桃園", None, -1))
        self.cB_depar_station.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "新竹", None, -1))
        self.cB_depar_station.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "苗栗", None, -1))
        self.cB_depar_station.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "台中", None, -1))
        self.cB_depar_station.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "彰化", None, -1))
        self.cB_depar_station.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "雲林", None, -1))
        self.cB_depar_station.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "嘉義", None, -1))
        self.cB_depar_station.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "台南", None, -1))
        self.cB_depar_station.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "左營", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "到達站", None, -1))
        self.cB_arrive_station.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "南港", None, -1))
        self.cB_arrive_station.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "台北", None, -1))
        self.cB_arrive_station.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "板橋", None, -1))
        self.cB_arrive_station.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "桃園", None, -1))
        self.cB_arrive_station.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "新竹", None, -1))
        self.cB_arrive_station.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "苗栗", None, -1))
        self.cB_arrive_station.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "台中", None, -1))
        self.cB_arrive_station.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "彰化", None, -1))
        self.cB_arrive_station.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "雲林", None, -1))
        self.cB_arrive_station.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "嘉義", None, -1))
        self.cB_arrive_station.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "台南", None, -1))
        self.cB_arrive_station.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "左營", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "出發時間", None, -1))
        self.cB_depar_time.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "00:00", None, -1))
        self.cB_depar_time.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "00:30", None, -1))
        self.cB_depar_time.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "06:00", None, -1))
        self.cB_depar_time.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "06:30", None, -1))
        self.cB_depar_time.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "07:00", None, -1))
        self.cB_depar_time.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "07:30", None, -1))
        self.cB_depar_time.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "08:00", None, -1))
        self.cB_depar_time.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "08:30", None, -1))
        self.cB_depar_time.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "09:00", None, -1))
        self.cB_depar_time.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "09:30", None, -1))
        self.cB_depar_time.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "10:00", None, -1))
        self.cB_depar_time.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "10:30", None, -1))
        self.cB_depar_time.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "11:00", None, -1))
        self.cB_depar_time.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "11:30", None, -1))
        self.cB_depar_time.setItemText(14, QtWidgets.QApplication.translate("MainWindow", "12:00", None, -1))
        self.cB_depar_time.setItemText(15, QtWidgets.QApplication.translate("MainWindow", "12:30", None, -1))
        self.cB_depar_time.setItemText(16, QtWidgets.QApplication.translate("MainWindow", "13:00", None, -1))
        self.cB_depar_time.setItemText(17, QtWidgets.QApplication.translate("MainWindow", "13:30", None, -1))
        self.cB_depar_time.setItemText(18, QtWidgets.QApplication.translate("MainWindow", "14:00", None, -1))
        self.cB_depar_time.setItemText(19, QtWidgets.QApplication.translate("MainWindow", "14:30", None, -1))
        self.cB_depar_time.setItemText(20, QtWidgets.QApplication.translate("MainWindow", "15:00", None, -1))
        self.cB_depar_time.setItemText(21, QtWidgets.QApplication.translate("MainWindow", "15:30", None, -1))
        self.cB_depar_time.setItemText(22, QtWidgets.QApplication.translate("MainWindow", "16:00", None, -1))
        self.cB_depar_time.setItemText(23, QtWidgets.QApplication.translate("MainWindow", "16:30", None, -1))
        self.cB_depar_time.setItemText(24, QtWidgets.QApplication.translate("MainWindow", "17:00", None, -1))
        self.cB_depar_time.setItemText(25, QtWidgets.QApplication.translate("MainWindow", "17:30", None, -1))
        self.cB_depar_time.setItemText(26, QtWidgets.QApplication.translate("MainWindow", "18:00", None, -1))
        self.cB_depar_time.setItemText(27, QtWidgets.QApplication.translate("MainWindow", "18:30", None, -1))
        self.cB_depar_time.setItemText(28, QtWidgets.QApplication.translate("MainWindow", "19:00", None, -1))
        self.cB_depar_time.setItemText(29, QtWidgets.QApplication.translate("MainWindow", "19:30", None, -1))
        self.cB_depar_time.setItemText(30, QtWidgets.QApplication.translate("MainWindow", "20:00", None, -1))
        self.cB_depar_time.setItemText(31, QtWidgets.QApplication.translate("MainWindow", "20:30", None, -1))
        self.cB_depar_time.setItemText(32, QtWidgets.QApplication.translate("MainWindow", "21:00", None, -1))
        self.cB_depar_time.setItemText(33, QtWidgets.QApplication.translate("MainWindow", "21:30", None, -1))
        self.cB_depar_time.setItemText(34, QtWidgets.QApplication.translate("MainWindow", "22:00", None, -1))
        self.cB_depar_time.setItemText(35, QtWidgets.QApplication.translate("MainWindow", "22:30", None, -1))
        self.cB_depar_time.setItemText(36, QtWidgets.QApplication.translate("MainWindow", "23:00", None, -1))
        self.cB_depar_time.setItemText(37, QtWidgets.QApplication.translate("MainWindow", "23:30", None, -1))
        self.b_send_selectedtrain.setText(QtWidgets.QApplication.translate("MainWindow", "送出選擇車次", None, -1))
        self.lineEdit_ID.setText(QtWidgets.QApplication.translate("MainWindow", "A114050073", None, -1))
        self.lineEdit_ID.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "ID", None, -1))
        self.lineEdit_phone.setText(QtWidgets.QApplication.translate("MainWindow", "0912855962", None, -1))
        self.lineEdit_phone.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "phone", None, -1))

